# Generated by Django 4.2.7 on 2023-12-04 13:05

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_project_coverimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="client",
            field=models.CharField(default="Client", max_length=100),
        ),
        migrations.AddField(
            model_name="project",
            name="image1",
            field=models.FileField(
                blank=True,
                upload_to=projects.models.project_image_directory,
                verbose_name="Image 1",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="image2",
            field=models.FileField(
                blank=True,
                upload_to=projects.models.project_image_directory,
                verbose_name="Image 2",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="image3",
            field=models.FileField(
                blank=True,
                upload_to=projects.models.project_image_directory,
                verbose_name="Image 3",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="image4",
            field=models.FileField(
                blank=True,
                upload_to=projects.models.project_image_directory,
                verbose_name="Image 4",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="shortname",
            field=models.CharField(default="Project", max_length=20),
        ),
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[
                    ("web", "Web Design"),
                    ("mobile", "Mobile"),
                    ("wordpress", "Wordpress"),
                    ("ecommerce", "E-commerce"),
                ],
                default="web",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="coverimage",
            field=models.FileField(
                blank=True, upload_to="project_images/", verbose_name="Cover Image"
            ),
        ),
    ]
