# Generated by Django 4.2.7 on 2023-12-04 21:22

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_project_client_project_image1_project_image2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image5",
            field=models.FileField(
                blank=True,
                upload_to=projects.models.project_image_directory,
                verbose_name="Image 5",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="client",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="project",
            name="shortname",
            field=models.CharField(max_length=50),
        ),
    ]
