# Generated by Django 4.2.7 on 2023-12-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_project_image5_alter_project_client_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="shortname",
            field=models.CharField(
                help_text="Short name for the project, lowercase, hyphenated. Also serves as name for media folder.",
                max_length=50,
            ),
        ),
    ]
