# Generated by Django 5.1.2 on 2024-10-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_alter_project_shortname"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="link_text",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="project",
            name="date",
            field=models.DateField(max_length=20),
        ),
    ]
