# Generated by Django 5.1.2 on 2024-10-14 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_project_link_text_alter_project_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="image1",
        ),
        migrations.RemoveField(
            model_name="project",
            name="image2",
        ),
        migrations.RemoveField(
            model_name="project",
            name="image3",
        ),
        migrations.RemoveField(
            model_name="project",
            name="image4",
        ),
        migrations.RemoveField(
            model_name="project",
            name="image5",
        ),
    ]
