# Generated by Django 5.1.2 on 2024-10-14 19:46

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_remove_project_image1_remove_project_image2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image1",
            field=models.FileField(
                blank=True,
                upload_to=projects.models.project_image_directory,
                verbose_name="Image 1",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="image2",
            field=models.FileField(
                blank=True,
                upload_to=projects.models.project_image_directory,
                verbose_name="Image 2",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="image3",
            field=models.FileField(
                blank=True,
                upload_to=projects.models.project_image_directory,
                verbose_name="Image 3",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="image4",
            field=models.FileField(
                blank=True,
                upload_to=projects.models.project_image_directory,
                verbose_name="Image 4",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="image5",
            field=models.FileField(
                blank=True,
                upload_to=projects.models.project_image_directory,
                verbose_name="Image 5",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="image6",
            field=models.FileField(
                blank=True,
                upload_to=projects.models.project_image_directory,
                verbose_name="Image 6",
            ),
        ),
    ]
