# Generated by Django 5.1.2 on 2024-10-14 19:47

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_project_image1_project_image2_project_image3_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image7",
            field=models.FileField(
                blank=True,
                upload_to=projects.models.project_image_directory,
                verbose_name="Image 7",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="image8",
            field=models.FileField(
                blank=True,
                upload_to=projects.models.project_image_directory,
                verbose_name="Image 8",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="image9",
            field=models.FileField(
                blank=True,
                upload_to=projects.models.project_image_directory,
                verbose_name="Image 9",
            ),
        ),
    ]
