# Generated by Django 5.1.2 on 2024-10-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_project_image10"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="id",
        ),
        migrations.AlterField(
            model_name="project",
            name="shortname",
            field=models.CharField(
                help_text=(
                    "URL short name for the project, lowercase, hyphenated. Also serves as name for media folder."
                ),
                max_length=50,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
