# Generated by Django 5.1.2 on 2024-10-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_remove_project_id_alter_project_shortname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[
                    ("web", "Web Design"),
                    ("mobile", "Mobile"),
                    ("wordpress", "Wordpress"),
                    ("e-commerce", "E-commerce"),
                ],
                default="web",
                max_length=20,
            ),
        ),
    ]
