# Generated by Django 5.1.2 on 2024-10-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResumeEducation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("date_attended", models.CharField(max_length=50)),
                ("study_details", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ResumeExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=100)),
                ("date_attended", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=100)),
                ("role_details", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ResumeSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("skill", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ResumeSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("bio", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("telephone", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=100)),
            ],
        ),
    ]
