# Generated by Django 5.1.2 on 2024-10-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumesummary",
            name="github_profile",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="resumesummary",
            name="linkedin_profile",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="resumesummary",
            name="bio",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
