# Generated by Django 5.1.2 on 2024-10-15 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0002_resumesummary_github_profile_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resumeeducation",
            options={"verbose_name_plural": "Resume Education"},
        ),
        migrations.AlterModelOptions(
            name="resumeexperience",
            options={"verbose_name_plural": "Resume Experience"},
        ),
        migrations.AlterModelOptions(
            name="resumeskill",
            options={"verbose_name_plural": "Resume Skills"},
        ),
        migrations.AlterModelOptions(
            name="resumesummary",
            options={"verbose_name_plural": "Resume Summary"},
        ),
    ]
