# Generated by Django 5.1.2 on 2024-10-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0003_alter_resumeeducation_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeskill",
            name="order",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
