# Generated by Django 5.1.2 on 2024-10-15 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0005_alter_resumeskill_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resumeskill",
            name="order",
        ),
    ]
