# Generated by Django 5.1.2 on 2024-10-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0007_resumeskill_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeeducation",
            name="position",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resumeexperience",
            name="position",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
